Added latest to tags; fixed chart oci version

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -93,7 +93,7 @@ jobs:
         run: |
           mkdir -p packages
           helm package ./ \
-            --version "${VERSION}" \
+            --version "v${VERSION}" \
             --destination packages
 
       - name: Login to GHCR
@@ -112,9 +112,36 @@ jobs:
             echo "Chart package ${CHART_TGZ} not found"
             exit 1
           fi
-
           helm push "${CHART_TGZ}" \
             "oci://${GHCR_REGISTRY}/${GHCR_NAMESPACE}"
+
+
+      - name: Package ${{ env.CHART_NAME }} chart (v0.0.0-latest)
+        run: |
+          # Save current Chart.yaml
+          cp Chart.yaml Chart.yaml.bak
+
+          # Set version to v0.0.0-latest
+          yq -i '.version = "v0.0.0-latest"' Chart.yaml
+
+          # Package chart with the "latest" version
+          helm package ./ \
+            --version "v0.0.0-latest" \
+            --destination packages
+
+          # Restore original Chart.yaml
+          mv Chart.yaml.bak Chart.yaml
+      - name: Push Helm chart to GHCR (OCI, v0.0.0-latest)
+        run: |
+          LATEST_TGZ="packages/${CHART_NAME}-v0.0.0-latest.tgz"
+          if [ ! -f "${LATEST_TGZ}" ]; then
+            echo "Chart package ${LATEST_TGZ} not found"
+            exit 1
+          fi
+          helm push "${LATEST_TGZ}" \
+            "oci://${GHCR_REGISTRY}/${GHCR_NAMESPACE}"
+
+
 
       - name: Copy packaged chart to subfolder (/charts/${{ env.CHART_NAME }})
         run: |
